version: 2
jobs:
  build:
    docker:
      - image: ubuntu-2204:current
    steps:
      - checkout
      - setup_remote_docker
      - run: make docker
  run:
    machine:
      - image: ubuntu-2204:current
    steps:
      - run: |
          docker run \
            --rm \
            --env-file <(env|grep PAGER_) \
            theo01/oci-arm-host-capacity:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
         filters:
          branches:
            only: main
          context:
            - docker
  run:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - run
